import { v4 as uuidv4 } from "uuid";

// IMPORTANT: CURRENTLY, THE CONVERSATION ID IS BEING PROCESSED, AS 
// UPDATING AT EVERY PAGE RELOAD. THERE IS NO DYNAMIC LOGIC FOR UNDERSTANDIONG WHEN 
// ONE PERSON LEFT, AND ANOTHER MAY HAVE COME ALONG. 
export const currentConversationId = uuidv4();